### ISSUE TITLE
Rewrite ocurrent.org website

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocurrent.org#7]
**Real World OCurrent** will be a re-write of the current website to produce a centralised source for ocurrent (similar to irmin.org). Proposal here: https://hackmd.io/vpbpVJ0uR42eRBCXUYGjpQ?view

**Comment by maiste** [comment]
This is an overview of what needs to be done with this PR:
- [X] Create the new base and the `Hugo` infrastructure
- [ ] Write the pipeline to keep the data up to date (@maiste)
- [ ] Verify with MDX the code in the different examples
- [ ] Redesign the entire branding
- [ ] Improve the community part
